### ISSUE TITLE
Is it safe to use crystal-mysql?

### ISSUE THREAD

**Issue by airinfection** [crystal-lang/crystal-mysql#19]
Is it safe to use crystal-mysql against sql injection etc? 
or how can i filter the input?

**Comment by spalladino** [comment]
@airinfection yes. The default methods for running queries that accept arguments will use MySQL prepared statements, which send the query parameters separately; this should take care of SQL parameter injection. 

In other words, make sure you do:
```crystal
db.exec "insert into contacts values (?, ?)", name, age
```

And *never ever* do:
```crystal
db.exec "insert into contacts values ('#{name}', #{age})"
```

Let me know if this answers your question!

**Comment by airinfection** [comment]
perfect ty. i am using "insert into contacts (name,age) values (?,?)", name, age
