### ISSUE TITLE
crystal-db 0.4.0 release?

### ISSUE THREAD

**Issue by drujensen** [crystal-lang/crystal-mysql#32]
Hi @bcardiff. Will there be a release for 0.4.0 soon?  I prefer not pointing to master.

**Comment by bcardiff** [comment]
crystal-mysql 0.3.2 is released and uses crystal-db 0.4.0. 

There is only 1 commit ahead of 0.3.2. 

Am i missing something?

**Comment by drujensen** [comment]
@bcardiff No, my bad.  wrong project.  SqlLite needs to be released.
