### ISSUE TITLE
Converting MySql::ResultSet to JSON::any

### ISSUE THREAD

**Issue by kazzkiq** [crystal-lang/crystal-mysql#42]
I'm trying to run a simple code and return a JSON with the results:

```ruby
DB.open("mysql://root@localhost:3306/mydb") do |db|
  db.query "SELECT name FROM users" do |result|
    result.to_json
  end
end
```

But I get this error when trying to use `.to_json` on the results:

```bash
no overload matches 'MySql::ResultSet#to_json' with type JSON::Builder
```

Any idea on how can I convert my query results to JSON? I can't find any documentation describing it, and its literally the only thing keeping me from releasing a small Crystal API module into production.

**Comment by bcardiff** [comment]
Crystal stdlib does not has a `Object#to_json`. Depending on your use case you might need to use a JSON::Builder or use JSON.mapping [docs](https://crystal-lang.org/api/0.23.1/JSON.html).

You might find https://manas.tech/blog/2017/01/16/from-a-db-to-json-with-crystal.html useful.
