### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by faustinoaq** [crystal-lang/crystal-mysql#48]
Hi @bcardiff 

v0.3.2 was released on Mar 21, at least 10 commit and fixes has been published on master.

Would be good to have a new release

Thanks you for maintain this shard! <3

**Comment by RX14** [comment]
👍 . This needs a new release as the latest release has bugs which are very common 9concurrent queries).

**Comment by bcardiff** [comment]
v0.3.3 released :shipit:
