### ISSUE TITLE
Crystal 0.24

### ISSUE THREAD

**Issue by lipanski** [crystal-lang/crystal-mysql#49]
There's a Crystal 0.24 pre-release that introduces [some breaking changes](https://github.com/crystal-lang/crystal/releases/tag/0.24.0). Do you have any plans to update for these changes and maybe make a 0.24 branch available?

**Comment by bcardiff** [comment]
Yes, but PR are welcome if you want to take the lead. I don’t think I would have time this week to make it.

Having a crystal-0.24 branch seems a good way to go.

**Comment by lipanski** [comment]
I gave it a shot here - https://github.com/crystal-lang/crystal-mysql/pull/50
let me know what you think :green_apple:

**Comment by lipanski** [comment]
@bcardiff now that 0.24.1 is out and Travis is pointing to the new version, could you merge the 0.24 branch into master please?

**Comment by lipanski** [comment]
thanks!
